### ISSUE TITLE
Given the saliency image, how to get the warped grid ?

### ISSUE THREAD

**Issue by mylifeasazucchini** [tchittesh/fovea#1]
Hi dear authors!

Thank you very much for sharing your work! I am quite interested in the concept of intelligent down-scaling but I am struggling with getting a modular version of this particular block to run : 

https://github.com/tchittesh/fovea/blob/4974b7b4ce912d25a19e51f82644e928750bce29/fovea/models/grid_generator.py#L311

My code keep running into dimension mismatch error while calculating weighted offsets on line 169 of the same file. And installing mmdetection is proving to be hassle so I could not get your whole code to run to check it myself.

So lets say I have an RGB image of size 1024x1024x3 and a saliency image of 1024x1024, what would be the values of the following parameters: output_shape and grid_shape ? (Because padding and other parameters are derived from it and the problem comes with matrix multiplication compatibility)

I have tried looking at the base paper but the math was not too clear to me. Apologies for my naivety! Any help will be much appreciated!!

**Comment by tchittesh** [comment]
Hi! Super excited to see our work getting used!

`grid_shape` just refers to the size of the saliency image. However, it might be worth it to downsample your saliency image and use a smaller `grid_shape` for efficiency's sake. A reasonable value might be 31x31. Increasing the dimensions of this will result in a smoother and more flexible warp at the cost of efficiency. Note: As you scale your `grid_shape`, you'll have to proportionally scale `attraction_fwhm`.

Essentially, at a high level, the code takes in the saliency image of shape `grid_shape`, say (x+1,x+1). Then, it pads the saliency to allow convolution with a global receptive field, making the `total_shape` (3x+1, 3x+1). Then, we apply global convolutions to compute the warp at each point in the grid of shape `grid_shape`. Finally, we upsample the transformation to shape `output_shape` and use bilinear interpolation on the full size image to end up with an intelligently downsampled image of shape `output_shape`. So if you want to run your detector on only a 256x256x3 image, `output_shape` should be 256x256.

Continuing the previous setup, on line 169, with a batch size B, `P` and `saliency_cat` should both have shape (B, 2, 3x+1, 3x+1). After line 169, `weighted_offsets` should have shape (2B, 1, 3x+1, 3x+1).

Let me know if that resolves your issues! If not, perhaps providing the `grid_shape` and shapes of `P` and `saliency_cat` on that line could help me figure out what's going on.

**Comment by mylifeasazucchini** [comment]
Thank you so much for the quick and in-depth explanation! And also I am happy to report that based on your suggestion I solved my problem! :) But could you please give a closing statement regarding the "attraction_fwhm" value. I understand that it must be proportional to the grid shape but is there some thumb rule to decide on the approximate value ? I am asking because I have been experimenting with it for a while now and a low value of fwhm leads to downscaled image converging to the same you would get by traditional down-scaling while a higher value would lead to heavy warping and maybe even detector failure.

Thanks once again!

**Comment by tchittesh** [comment]
Yup, those observations are in line with ours. Smaller fwhms lead to weaker more local warping, which can be better for multimodal saliency distributions, whereas higher fwhms lead to stronger more global warping.

In our experiments, for our grid_shape of 31x51, we used an fwhm of 13, which worked well for uni and bimodal saliency distributions.
