### ISSUE TITLE
The input image resolution

### ISSUE THREAD

**Issue by tjyuyao** [tchittesh/fovea#3]
It seems that the experiment resolution of 960x600 (0.5x) mentioned in the paper is not correctly implemented in the dataset config file, which has a resize config with (1333x800) resolution. Am I missing anything or should I believe the config file?

**Comment by tchittesh** [comment]
Lots of fields in the configs get changed dynamically during runtime by [`config.py`](https://github.com/tchittesh/fovea/blob/c8707bd2e4f10678f6636d24c2915a43b44a59ed/fovea/utils/config.py). The best way to view the final generated configs is to actually run the scripts and see [what gets printed](https://github.com/tchittesh/fovea/blob/c8707bd2e4f10678f6636d24c2915a43b44a59ed/tools/test.py#L62).

For our FOVEA KDE experiments, this field gets changed to 1x (1920x1200) resolution by the `--preprocess-scale` flag. Then, the full scale image gets adaptively downsampled to 960x600 (e.g. [here](https://github.com/tchittesh/fovea/blob/c8707bd2e4f10678f6636d24c2915a43b44a59ed/configs/models/fixed_kde_grid.py#L4)).

**Comment by tjyuyao** [comment]
Thanks for your reply, I understand now.
