### ISSUE TITLE
What is unwarp_bboxes doing

### ISSUE THREAD

**Issue by ShenZheng2000** [tchittesh/fovea#4]
Hello, author! Thanks for your nice work. 

I would like to know what [unwarp_bboxes ](https://github.com/tchittesh/fovea/blob/c8707bd2e4f10678f6636d24c2915a43b44a59ed/fovea/models/grid_generator.py#L55C15-L55C15)is doing. It seems like it is transforming warp bboxes back to unwarpped bboxes. However, it is unclear how you obtain the warpped bboxes from original bboxes. Could you share the code to do that?

**Comment by tchittesh** [comment]
Hi! The intended use case for that function is actually to post-process model outputs. The pipeline is:

input image -> warped input image -> model forward pass -> warped predicted bboxes -> unwarped predicted bboxes

**Comment by ShenZheng2000** [comment]
Yes, I understand your procedure. In another project, I am utilizing your image warpping technique to warp the groundtruth bboxes (instead of unwarping the predicted bboxes). That requires a "warp_bboxes" function, which does the opposite thing to unwarp_bboxes(). Hope you can tell me how to write that function.

**Comment by tchittesh** [comment]
Ah, that's useful context. As far as I'm aware, `warp_bboxes` would require actually inverting the image warp. You could try using the warp inversion function from [LZU](https://github.com/tchittesh/lzu/blob/main/lzu/invert_grid.py) for this.

It would roughly look like
```
def warp_bboxes(bboxes, grid, output_shape):
    inverse_grid = invert_grid(grid, inverse_grid_shape)
    return unwarp_bbozes(bboxes, inverse_grid, output_shape)
```
I believe `inverse_grid_shape` can be chosen to be anything (controls how precise the inverse calculation would be).

**Comment by ShenZheng2000** [comment]
Thanks so much! I have managed to solve the bbox warping using the following code
```
def warp_bboxes(bboxes, grid, separable=True):
    size = grid.shape
    inverse_grid_shape = torch.Size((size[0], size[3], size[1], size[2]))

    inverse_grid = invert_grid(grid, inverse_grid_shape, separable) 
    bboxes = unwarp_bboxes(bboxes, inverse_grid.squeeze(0), size[1:3])
    return bboxes

```
