### ISSUE TITLE
shell script for training on BDD100K

### ISSUE THREAD

**Issue by ShenZheng2000** [tchittesh/fovea#5]
The paper mentions experiments on both BDD and AVHD datasets. However, I couldn't find the initial training files (.sh or .py) for BDD. Could you kindly share the BDD-related files? Thanks.

**Comment by tchittesh** [comment]
Hi! Sorry, I don't have those available. Those experiments were done by @mtli -- perhaps you could contact him for more details.

**Comment by mtli** [comment]
Sorry for the late reply! We didn't release this code or scripts, but you might find these two files useful. The first is a standalone script that converts the BDD dataset into AVHD format, and the second file is the mmdet-style config for the converted BDD dataset.

[bdd_utils.zip](https://github.com/tchittesh/fovea/files/12640075/bdd_utils.zip)

**Comment by ShenZheng2000** [comment]
Thanks so much! @mtli
